added loadgen manifests to check

diff --git a/.github/workflows/check-tags.yml b/.github/workflows/check-tags.yml
--- a/.github/workflows/check-tags.yml
+++ b/.github/workflows/check-tags.yml
@@ -37,8 +37,12 @@ jobs:
             expected_telemetry="test"
         fi
         # check manifests
-        num_files=$(cat kubernetes-manifests/* | grep image | grep stackdriver-sandbox-230822 | wc -l)
-        num_tagged=$(cat kubernetes-manifests/* | grep image | grep stackdriver-sandbox-230822 | grep "$expected_tag_regex" | wc -l)
+        num_files=$(cat *-manifests/* | grep image | grep stackdriver-sandbox-230822 | wc -l)
+        num_tagged=$(cat *-manifests/* | grep image | grep stackdriver-sandbox-230822 | grep "$expected_tag_regex" | wc -l)
+        if [[ "$num_tagged" -lt 11 ]]; then
+            echo "missing manifests"
+            exit 1
+        fi
         if [[ "$num_tagged" != "$num_files" ]]; then
           echo "manifests have incorrect tag"
           exit 1
